#!/usr/bin/env python3
"""Regenerate the built-in payload corpus embedded in rcekit.py.

``templates/payloads.json`` stays the single source of truth: contributors edit
it, and this script copies it into ``rcekit.py`` so a lone ``rcekit.py`` — copied
onto a jump box, fetched with ``curl``, installed without its data files — still
has a corpus to run.

    python tools/embed_corpus.py            # rewrite the embedded block
    python tools/embed_corpus.py --check    # exit 1 if it is out of date

``tests/test_corpus_embedding.py`` fails when the two drift, so a corpus change
that skips this script cannot reach main.
"""

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SCRIPT = REPO_ROOT / "rcekit.py"
CORPUS = REPO_ROOT / "templates" / "payloads.json"

BEGIN = "# --- BEGIN EMBEDDED PAYLOAD CORPUS (generated by tools/embed_corpus.py) ---"
END = "# --- END EMBEDDED PAYLOAD CORPUS ---"


def render(corpus_text):
    """Render the corpus as a raw triple-quoted literal.

    Raw is mandatory: the corpus carries ~700 backslashes (Windows paths such as
    ``C:\\\\Windows\\\\System32``), and a cooked string would let Python consume
    the JSON's own escaping before json.loads ever sees it.

    It stays pretty-printed rather than compacted or base64-encoded so that a
    change to any payload shows up as a readable diff — in a security tool, a
    reviewable corpus diff is a safety property, not a style preference.
    """
    if '"""' in corpus_text:
        raise SystemExit("corpus contains a triple quote; cannot embed as a triple-quoted literal")
    if corpus_text.rstrip("\n").endswith("\\"):
        raise SystemExit("corpus ends with a backslash; cannot embed as a raw literal")
    body = corpus_text.strip("\n")
    return (
        f"{BEGIN}\n"
        f"# Source: templates/payloads.json — edit that file, then re-run the script.\n"
        f'EMBEDDED_PAYLOAD_CORPUS = r"""\n'
        f"{body}\n"
        f'"""\n'
        f"{END}"
    )


def splice(script_text, block):
    start = script_text.find(BEGIN)
    end = script_text.find(END)
    if start == -1 or end == -1:
        raise SystemExit(f"markers not found in {SCRIPT}")
    return script_text[:start] + block + script_text[end + len(END):]


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="verify the embedded corpus is current; do not write")
    args = parser.parse_args()

    corpus_text = CORPUS.read_text(encoding="utf-8")
    json.loads(corpus_text)  # never embed something that does not parse

    script_text = SCRIPT.read_text(encoding="utf-8")
    updated = splice(script_text, render(corpus_text))

    if updated == script_text:
        print("embedded corpus is up to date")
        return 0
    if args.check:
        print("embedded corpus is STALE — run: python tools/embed_corpus.py", file=sys.stderr)
        return 1

    SCRIPT.write_text(updated, encoding="utf-8")
    print(f"embedded corpus updated from {CORPUS.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
